version: '3'

services:
  backend:
    image: REGISTRY/REPOSITORY:VERSION
    container_name: backend
    restart: always
    ports:
      - 80:5000
    depends_on:
      - db
  db:
    image: mongo:5.0
    restart: always
    container_name: db
    ports:
      - 27017:27017
  
